# Generated by Django 4.1.7 on 2023-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default=True, max_length=255, unique=True)),
                ('address', models.CharField(max_length=400)),
                ('photo', models.ImageField(upload_to='media/')),
                ('designation', models.CharField(blank=True, choices=[('Front-end-developer', 'Front-end-developer'), ('Back-end-developer', 'Back-end-developer'), ('Team-Leader', 'Team-Leader'), ('Manager', 'Manager'), ('Quality-Analyst', 'Quality-Analyst')], default=True, max_length=255)),
            ],
        ),
    ]
